[project]
name = "captcha-solver-coursework"
version = "0.1.0"
description = "Modification of yeguixin/captcha_solver to satisfy coursework requirements"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
